version: '3'
services:
  kiwi:
    build:
      context: .
    working_dir: /home/ctf
    container_name: kiwi
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "10044:9999"
    entrypoint: /etc/init.sh
    restart: always
