version: '3'
services:
  str_vs_cstr:
    build:
      context: .
    working_dir: /home/pwn
    container_name: str_vs_cstr
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9003:9999"
    entrypoint: /etc/init.sh
    restart: always
