version: '3'
services:
  smal_arey:
    build:
      context: .
    working_dir: /home/pwn
    container_name: smal_arey
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9002:9999"
    entrypoint: /etc/init.sh
    restart: always
